require("core.options")
-- require("core.treesitter")
require("core.lsp")
require("core.statusline")
require("core.snippet")

require("plugins.mini")
require("plugins.fzf")
require("plugins.catppuccin")
require("plugins.conform")
require("plugins.illuminate")
require("plugins.yanky")
require("plugins.crates")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.cmp")
require("plugins.indent-blankline")
